runtime: nodejs18

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /script.js
  static_files: script.js
  upload: script.js

- url: /styles.css
  static_files: styles.css
  upload: styles.css

# - url: /.*
#   static_dir: .
